username: Speeson
template: classic  # Estilo clásico
languages: 1        # Mostrar los lenguajes más usados
isocalendar: 1      # Mostrar calendario de contribuciones
config:
  timezone: Europe/Madrid
  title: "Speeson's GitHub Metrics"  # Título personalizado
  theme: dark  # Puedes elegir entre "dark" y "light" para el tema
  hide:
    - achievements  # Puedes ocultar los logros si prefieres que no aparezcan
  custom_title:
    text: "Speeson's Development Journey"  # Título personalizado
    font_size: 30  # Tamaño de fuente
    font_weight: bold  # Negrita para destacar el título
